### ISSUE TITLE
Error in the first epoch in the train.py file

### ISSUE THREAD

**Issue by normalusername1** [kampta/face-seg#2]
I downloaded the data and set everything up on google colab but I get some sort of division by 0 error which I don't really know how to fix. If I add a temporary fix to the train.py file, I get different errors instead. 
`================== Epoch: 1 ==================
Traceback (most recent call last):
  File "/content/face-seg/train.py", line 198, in <module>
    main()
  File "/content/face-seg/train.py", line 95, in main
    train_loss = train(train_loader, model, optimizer, criterion)
  File "/content/face-seg/train.py", line 43, in train
    epoch_loss = running_loss / count
ZeroDivisionError: float division by zero`

That is the error I am getting. My code is set up as so

`!python '/content/face-seg/train.py' \
    --data-folder '/content/drive/My Drive/data (1)'\
    --pre-trained '/content/face-seg/weights/mobilenet_v2.pth.tar' \
    --output-folder '/content/scratch' \
    --num-epochs=50 \
    --batch-size=32`

**Comment by kampta** [comment]
It looks like your `count=0` in the line 43, which probably means your `train_loader` is empty. Check if your data is set up properly.

**Comment by thebossman1093** [comment]
Ok I realized my mistake. It was actually quite a basic error. Instead of the data being '/content/drive/My Drive/data (1)', it should be '/content/drive/My Drive/data (1)/raw'

**Comment by normalusername1** [comment]
Ok I figured out my mistake, it was actually quite basic. Instead of being '/content/drive/My Drive/data (1)', it should be '/content/drive/My Drive/data (1)/raw'
